name: Waka Readme

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TIMEZONE: "False"
          BADGE_STYLE: "flat"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          IGNORED_REPOS: "ok-wuthering-waves,WutheringWavesUID,VGA_FPGA_GameDesign,ADDs_Proj,Mbed-code-for-Sophomore,Mbed-code-for-Sophomore-2,PT1000-Proj,ECE550,ECE550_GameDesign,NEXTJS_DASHBOARD,ESP32SwitchActuator,moegirl-mcp"
